FROM docker.io/arm32v7/golang:1.17.7 as builder
WORKDIR /work
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=7 go build -a -o app .

# ---
FROM docker.io/arm32v7/busybox:1.35.0

ENV HOST=0.0.0.0
ENV PORT=3000

RUN mkdir /app
RUN addgroup -S app && adduser -S -G app app
WORKDIR /app

COPY --from=builder /work/app .

RUN chown -R app:app .
USER app

EXPOSE 3000

ENTRYPOINT [ "./app" ]
